config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'auth/wunderlist/callback', to: 'sessions#wunderlist'
  get 'auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  post 'sessions/subscribe', to: 'sessions#subscribe'
  root "sections#index"
  get '/sections/created',to: 'sections#created', as: "created_sections"
  get '/sections/:id/modify',to: 'sections#modify', as: "modify_section"
  get '/sections/assigned',to: 'sections#assigned', as: "assigned_sections"
  resources :sections
  post 'sections/:id/assign', to: 'sections#assign', as: "assign_section"
  resources :modifications
  resources :reviews
  resources :notifications
end

app/views/shared/_comment.html.erb
<div class='row' style="margin-top: 20px;">
  <div class="col-md-12">
    <h3 style="font-size: 16px; color: #ABA8A6;">其他评论</h3>
  </div>
  <div class="col-md-12">
    <% unless @reviews.blank? %>
  <ul class="timeline">
    <% @reviews.each do |review| %>
      <li>
        <div class="timeline-badge">
    <%= image_tag review.user.avatar_url %>
        </div>
        <div class="timeline-panel">
          <div class="timeline-heading">
            <span class="timeline-title"><%= review.user.name%></span>
            <span class="pull-right">&nbsp <%= time_ago_in_words(review.updated_at)%> ago<span>
          </div>
          <hr>
          <div class="timeline-body markdown">
            <%== review.content %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
<% end %>
</div>
</div>
<%= render "shared/comment_box", partial: true %>

app/views/shared/_comment_box.html.erb
<div class="row pull-right comment-box-btn">
  <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#comment_box">添加评论</button>
</div>
<div class="row collapse pull-right" id="comment_box">
<%= simple_form_for(@review, html: { class: 'form-horizontal' }) do |f| %>
  <div class="col-md-8">
    <%= f.input :content, label: false, :input_html => { :ckeditor => { :height => 200, :toolbar=> 'mini' } }, :label_html => { style: "font-size: 12px; color: #ABA8A6;" }, as: :ckeditor %>
  </div>
  <%= f.input :rating, input_html: {id: "review_rating"},  as: :hidden %>
  <%= f.input :section_id, input_html: {value: @section.id},  as: :hidden %>
  <div class="col-md-12">
    <%= f.button :submit, "提交", class: "btn btn-info col-md-8" %>
  </div>
<% end %>
</div>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %> 

app/views/shared/_float_icon.html.erb
<div id="inbox">
  <div class="fab btn-group show-on-hover dropup">
      <div data-toggle="tooltip" data-placement="left" title="Compose" style="margin-left: 42px;">
  <button type="button" class="btn btn-danger btn-io dropdown-toggle" data-toggle="dropdown">
    <span class="fa-stack fa-2x">
        <i class="fa fa-circle fa-stack-2x fab-backdrop"></i>
        <i class="fa fa-plus fa-stack-1x fa-inverse fab-primary"></i>
        <i class="fa fa-pencil fa-stack-1x fa-inverse fab-secondary"></i>
    </span>
  </button></div>
  <ul class="dropdown-menu dropdown-menu-right" role="menu">
      <li><a href="<%= sections_path %>" data-toggle="tooltip" data-placement="left" title="首页"><i class="fa fa-home"></i></a></li>
    <% if current_user %>
        <li><a href="<%= new_section_path %>" data-toggle="tooltip" data-placement="left" title="写ES"><i class="fa fa-pencil"></i></a></li>
      <% if can? :modify, Section %>
        <li><a href="<%= assigned_sections_path %>" data-toggle="tooltip" data-placement="left" title="批改ES"><i class="fa fa-eraser"></i></a></li>
      <% end %>
      <li><a href="<%= created_sections_path %>" data-toggle="tooltip" data-placement="left" title="我的ES"><i class="fa fa-file-text-o"></i></a></li>
      <li>
        <%=link_to content_tag(:i, '', class: 'fa fa-sign-out'), logout_path, "data-toggle": "tooltip", "data-placement": "left", title: "退出登陆"%>
      </li>
    <% else %>
      <li>
        <%=link_to content_tag(:i, '', class: 'fa fa-sign-in'), '/auth/qilian', "data-toggle": "tooltip", "data-placement": "left", title: "登陆"%>
      </li>
    <% end %>
  </ul>
</div>
</div>

app/views/shared/_float_icon_section.html.erb
<div id="inbox">
  <div class="fab btn-group show-on-hover dropup">
      <div data-toggle="tooltip" data-placement="left" title="Compose" style="margin-left: 42px;">
  <button type="button" class="btn btn-danger btn-io dropdown-toggle" data-toggle="dropdown">
    <span class="fa-stack fa-2x">
        <i class="fa fa-circle fa-stack-2x fab-backdrop"></i>
        <i class="fa fa-plus fa-stack-1x fa-inverse fab-primary"></i>
        <i class="fa fa-pencil fa-stack-1x fa-inverse fab-secondary"></i>
    </span>
  </button></div>
  <ul class="dropdown-menu dropdown-menu-right" role="menu">
      <li><a href="<%= sections_path %>" data-toggle="tooltip" data-placement="left" title="首页"><i class="fa fa-home"></i></a></li>
    <% if current_user %>
        <li><a href="<%= new_section_path %>" data-toggle="tooltip" data-placement="left" title="写ES"><i class="fa fa-pencil"></i></a></li>
      <% if current_user.teacher? %>
        <li><a href="<%= assigned_sections_path %>" data-toggle="tooltip" data-placement="left" title="批改ES"><i class="fa fa-eraser"></i></a></li>
      <% end %>
      <li><a href="<%= created_sections_path %>" data-toggle="tooltip" data-placement="left" title="我的ES"><i class="fa fa-file-text-o"></i></a></li>
      <li>
        <%=link_to content_tag(:i, '', class: 'fa fa-sign-out'), logout_path, "data-toggle": "tooltip", "data-placement": "left", title: "退出登陆"%>
      </li>
    <% else %>
      <li>
        <%=link_to content_tag(:i, '', class: 'fa fa-sign-in'), '/auth/qilian', "data-toggle": "tooltip", "data-placement": "left", title: "登陆"%>
      </li>
    <% end %>
  </ul>
</div>
</div>

app/views/shared/_header.html.erb
<header class='header'>
  <div class="container">
    <div class="row">
      <div class="col-md-3 brand">
        <a class="brand-title" href='/'>大家的ES</a>
        <span class="subtitle">撰写，批改，过关 </span>
      </div>
      <div class="col-md-3 pull-right list-image-small">
        <% if current_user %>
          <div class="pull-right">
          <%=image_tag current_user.avatar_url %>
          <span>
           (发表：<%=current_user.created_sections.count%>篇, 修改: <%=current_user.modified_sections.count %>篇)
          </span>
        </div> 
        <% if current_user.wunderlist_token.blank? %>
          <a href="/auth/wunderlist" title="关联wunderlist"><%=image_tag image_path('wunderlist.png')%></a>
        <% end %>
        <% end %>
      </div>
    </div>
  </div>
</header>