config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'auth/wunderlist/callback', to: 'sessions#wunderlist'
  get 'auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  post 'sessions/subscribe', to: 'sessions#subscribe'
  root "sections#index"
  get '/sections/created',to: 'sections#created', as: "created_sections"
  get '/sections/:id/modify',to: 'sections#modify', as: "modify_section"
  get '/sections/assigned',to: 'sections#assigned', as: "assigned_sections"
  resources :sections
  post 'sections/:id/assign', to: 'sections#assign', as: "assign_section"
  resources :modifications
  resources :reviews
  resources :notifications
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :author, class_name: "User", foreign_key: "user_id", inverse_of: :created_sections
  belongs_to :assignee, class_name: "User", foreign_key: "assignee_id", optional: true, inverse_of: :assigned_sections
  has_one :modification, dependent: :delete
  has_many :section_tags, dependent: :destroy
  has_many :tags, class_name: "Tag", through: :section_tags
  has_many :reviews, dependent: :destroy
  has_many :reviewers, class_name: "User", through: :reviews, dependent: :destroy
  validates :title, presence: true, length: {maximum: 30}
  validates :content, presence: true
  paginates_per 10


  def message_recevers_ids
    reviewers.uniq.pluck(:id)
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :authenticate, except: [:index]
  def index
    if current_user && !current_user.student?
      @sections = Section
    elsif current_user && current_user.student?
      @sections = Section.where(user_id: current_user.id).or(Section.where(visiable: true))
    else
      @sections = Section.where(visiable: true)
    end
    @sections = @sections.preload(:tags, :author, :assignee, :modification).order("created_at DESC").page params[:page]
  end

  def new
    if can? :create, Section
      @section = Section.new
    else
      flash[:error]="每小时只能发一篇哦！"
      redirect_to sections_path
    end
  end

  def edit
    @section = Section.find(params.permit(:id)[:id])
    unless can? :edit, @section
      flash[:error]="只能编辑自己的内容"
      redirect_to sections_path
    end
  end

  def update
    @section = Section.find(params.permit(:id)[:id])
    if can? :edit, @section
      if @section.update(section_params)
        flash[:success]="更新成功！"
        redirect_to sections_path
      else
        render :edit
      end
    else
      flash[:error]="只能编辑自己的内容"
      redirect_to sections_path
    end
  end

  def create
    unless can? :create, Section
      flash[:error]="每小时只能发一篇哦！"
      redirect_to sections_path
    end
    @section = current_user.created_sections.new(section_params)
    if @section.save
      flash[:success]="创建新的ES草稿成功！"
      redirect_to sections_path
    else
      render :new
    end
  end

  def show
    @section = Section.find(params.permit(:id)[:id])
    if can? :read, @section
      @reviews = @section.reviews.preload(:user)
      @modification = @section.modification
      @review = Review.new
    else
      flash[:error]="此ES设置成不可见了哦！"
      redirect_to root_path 
    end
  end


  def assign
    @section = Section.find(params.permit(:id)[:id])
    if can? :assign, @section
      @section.assignee = current_user
      @section.save
      WunderlistWorker.perform_async(current_user.id, "修改ES #{@section.title} #{modify_section_url(@section)}")
      render 'assign'
    else
      head 401
    end
  end

  def created
    @sections = current_user.created_sections.preload(:tags, :author, :assignee, :modification).order("created_at DESC").page params[:page]
    render :index
  end

  def assigned
    @sections = current_user.assigned_sections.preload(:tags, :author, :assignee, :modification).order("created_at DESC").page params[:page]
    render :index
  end


  def modify
    @section = Section.find(params.permit(:id)[:id])
    @modification = @section.modification || Modification.new
  end
  private

  def section_params
    params.require(:section).permit(:id,:content,:title, :visiable, :tag_ids=>[])
  end
  
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/assign.js.erb
$("#assignee_for_section_<%=@section.id%>").html('<span style="font-size: 12px; color: #ABA8A6;">修改指导: </span>' + "<img src='<%=@section.assignee.avatar_url%>' class='list-image'/>");

$("#list-meta-<%=@section.id%>").append('<a href="<%=modify_section_path(@section)%>" style="color: red">批改</a>')

app/views/sections/edit.html.erb
<div class="container content-body">
    <div class="col-md-6 col-md-offset-5">
      <h3>撰写新的ES</h3>
    </div>
      <%= simple_form_for(@section, html: { class: 'form-horizontal' }) do |f| %>
       <div class="row">
          <div class="col-md-10 col-md-offset-1">
            <%= f.input :title, label: "ES小项的标题" %>
          </div>
        </div>
       <div class="row">
          <div class="col-md-10 col-md-offset-1">
            <%= f.input :visiable, label: "所有人可见" %>
          </div>
        </div>
       <div class="row">
          <div class="col-md-10 text-editor col-md-offset-1">
            <%= f.input :content, label: "内容", :input_html => { :ckeditor => { :height => 350, :toolbar=> 'mini' } },  as: :ckeditor %>
          </div>
       </div>
       <div class="row">
          <div class="col-md-12 inline-block col-md-offset-1">
            <%= f.input :tag_ids, label: "选择标签", collection: Tag.all,  as: :check_boxes%>
          </div>
       </div>
       <div class="row" style="margin-top: 50px;">
          <%= f.button :submit, "提交", class: "btn btn-info col-xs-8 col-xs-offset-2" %>
       </div>
     <% end %>
</div>

app/views/sections/index.html.erb
<div class="container content-body">
  <div class="row">
    <% @sections.each do |section| %>
      <div class="col-md-12 list-content">
        <div class="list-image">
          <%=link_to image_tag(section.author.avatar_url), "https://forum.qilian.jp/#{section.author.login}", target: '_blank' %>
        </div>
        <div class="list-info">
          <div class="list-title">
            <span class="title-url"><%=link_to section.title, section_path(section) %></span>
            <% unless section.modification.blank? %>
              <i class="fa fa-check" aria-hidden="true"></i>
            <% end %>
          </div>
          <div id="assignee_for_section_<%= section.id %>" class="assignee list-image-small">
            <% if section.assignee.blank? %>
              <% if can? :modify, section %>
                <%= simple_form_for section, url: assign_section_path(section), method: :post, remote: true do |f|%>
                  <%=f.submit "我来修改", class: "btn btn-sm btn-danger" %>
                <% end %>
              <% end %>
            <% else %>
              <span style="font-size: 12px; color: #ABA8A6;">修改指导: </span>
              <%=link_to image_tag(section.assignee.avatar_url, class: 'list-image'), "https://forum.qilian.jp/#{section.assignee.login}", target: '_blank' %>
            <% end %>
          </div>
          <div class="list-meta" id="list-meta-<%=section.id%>">
              <span class='list-user'><%=section.author.name %></span> 发表于
              <%= time_ago_in_words section.created_at %> ago

              <%= link_to "编辑", edit_section_path(section) if current_user == section.author %>
              <%= link_to("批改", modify_section_path(section), style: "color: red") if (current_user && current_user == section.assignee)  %>
            </div>
          <div class="tags">
            <% section.tags.each do |tag| %>
              <%= link_to tag.name, "#", class: "success" %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="row">
      <div class="col-md-6 col-md-offset-4">
        <%= paginate @sections %>
      </div>
  </div>
</div>

app/views/sections/modify.html.erb
<div class="container content-body">
  <div class="row">
    <div class="col-md-6 col-md-offset-5">
      <h3>修改ES</h3>
    <div class="list-image">
      <%=image_tag @section.author.avatar_url %>
    </div>
    </div>
  </div>
    <%= simple_form_for(@modification, html: { class: 'form-horizontal' }) do |f| %>
      <div class="row">
        <div class="col-md-10 col-md-offset-1">
          <%= f.input :content, label: @section.title, :input_html => { :ckeditor => { :height => 350, :toolbar=> 'mini', }, value: @modification.content || @section.content },  as: :ckeditor %>
        </div>
          <%= f.input :section_id, input_html: {value: @section.id},  as: :hidden %>
       </div>
       <div class="row" style="margin-top: 100px;">
          <%= f.button :submit, "提交", class: "btn btn-info col-xs-8 col-xs-offset-2" %>
       </div>
      <% end %>
</div>

app/views/sections/new.html.erb
<div class="container content-body">
    <div class="col-md-6 col-md-offset-5">
      <h3>撰写新的ES</h3>
    </div>
      <%= simple_form_for(@section, html: { class: 'form-horizontal' }) do |f| %>
       <div class="row">
          <div class="col-md-10 col-md-offset-1">
            <%= f.input :title, label: "ES小项的标题" %>
          </div>
        </div>
       <div class="row">
          <div class="col-md-10 col-md-offset-1">
            <%= f.input :visiable, label: "所有人可见" %>
          </div>
        </div>
       <div class="row">
          <div class="col-md-10 text-editor col-md-offset-1">
            <%= f.input :content, label: "内容", :input_html => { :ckeditor => { :height => 350, :toolbar=> 'mini' } },  as: :ckeditor %>
          </div>
       </div>
       <div class="row">
          <div class="col-md-12 inline-block col-md-offset-1">
            <%= f.input :tag_ids, label: "选择标签", collection: Tag.all,  as: :check_boxes%>
          </div>
       </div>
       <div class="row" style="margin-top: 50px;">
          <%= f.button :submit, "提交", class: "btn btn-info col-xs-8 col-xs-offset-2" %>
       </div>
     <% end %>
</div>

app/views/sections/show.html.erb
<div class="container content-body section-detail">
  <div class="row">
      <div class="col-md-12">
          <div class="box">
              <div class="box-icon">
            <%= image_tag @section.author.avatar_url, class: "user-photo" %>
              </div>
              <div class="info">
                <h4 class="text-center"><%= @section.title %></h4>
		 <ul class="nav nav-tabs">
		  <li class="active"><a data-toggle="tab" href="#origin">原文</a></li>
		  <li><a data-toggle="tab" href="#modified">修改</a></li>
		</ul>
                <div class="tab-content">
		  <div id="origin" class="tab-pane fade in active content">
		    <p><%== @section.content%></p>
		  </div>
                  <div id="modified" class="tab-pane fade content">
                    <% if @modification.blank? %>
                      <div class="container">
                        <div class="row">
                          <div class="col-md-4 col-md-offset-2">
                            <a href="http://thecatapi.com"><img src="http://thecatapi.com/api/images/get?format=src&type=gif"></a>
                          </div>
                        </div>
                        <div class="row">
                          <div class="col-md-6 col-md-offset-4">
                            还木有修改，喵～
                          </div>
                        </div>
                      </div>
                    <% else %>
                      <p><%== @modification.content if @modification %></p>
                    <% end %>
		  </div>
		</div>
              </div>
          </div>
      </div>
</div>
   <%= render "shared/comment", partial: true %>
</div>